apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-{{.Values.Consul.PreInstall.ComponentName}}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{.Values.Consul.PreInstall.ComponentName}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "50"
data:
{{ (.Files.Glob "preInstallConsul/*").AsConfig | indent 2 }}
