{{- if .Values.Consul.Backup.Enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-{{.Values.Consul.Backup.ComponentName}}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Consul.Backup.ComponentName }}"
data:
  config.json : |
    {
      "server": false,
      "datacenter": "{{.Values.Consul.Datacenter}}",
      "retry_join": ["{{ template "vault.fullname" . }}-{{.Values.Consul.ComponentName}}"],
      "bind_addr": "0.0.0.0",
      "ca_file": "/consul/ca/ca.crt.pem",
      "cert_file": "/consul/tls/tls.crt",
      "key_file": "/consul/tls/tls.key",
      "client_addr": "127.0.0.1",
      "data_dir": "/consul/data"
    }
{{- end}}
