apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-{{.Values.Consul.ComponentName}}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Consul.ComponentName }}"
data:
  config.json : |
    {
      "server": true,
      "leave_on_terminate": true,
      "bind_addr": "0.0.0.0",
      "ca_file": "/consul/ca/ca.crt.pem",
      "cert_file": "/consul/tls/tls.crt",
      "client_addr": "0.0.0.0",
      "data_dir": "/consul/data",
      "datacenter": {{.Values.Consul.Datacenter | quote }},
      "key_file": "/consul/tls/tls.key",
      "ports": {
        "http": -1,
        "https": {{.Values.Consul.HttpPort}}
      },
      "verify_incoming_rpc": true,
      "verify_incoming_https": true,
      "verify_outgoing": true,
      "verify_server_hostname": true,
      "disable_anonymous_signature": true,
      "disable_update_check": true
    }
