apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
spec:
  {{- if not .Values.Vault.Ingress.Enabled }}
  type: NodePort
  {{-  end }}
  ports:
  - name: https
    port: {{.Values.Vault.HttpPort}}
    {{- if not .Values.Vault.Ingress.Enabled }}
    nodePort: {{.Values.Vault.NodePort}}
    {{- end }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
