---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "vault.fullname" . }}-{{.Values.Vault.ConsulClient.ComponentName}}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
data:
  config.json : |
    {
      "bind_addr": "0.0.0.0",
      "ca_file": "/consul/ca/ca.crt.pem",
      "cert_file": "/consul/tls/tls.crt",
      "data_dir": "/consul/data",
      "datacenter": {{.Values.Consul.Datacenter | quote }},
      "key_file": "/consul/tls/tls.key",
      "addresses": {
        "http": "unix:///consul-unix-socket/consul-client.sock"
      },
      "unix_sockets": {
        "mode": "600"
      },
      "ports": {
        "http": {{.Values.Consul.HttpPort}},
        "https": -1
      },
      "client_addr": "0.0.0.0",
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true
    }
