{{- if .Values.Vault.Tls.LetsEncrypt.Enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.PreInstall.ComponentName }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "100"
spec:
  activeDeadlineSeconds: {{.Values.Vault.PreInstall.JobDeadline}}
  template:
    metadata:
      name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
      labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.PreInstall.ComponentName }}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
        image: "{{.Values.Misc.letsencrypt.Image}}:{{.Values.Misc.letsencrypt.ImageTag}}"
        imagePullPolicy: "Always"
        env:
          - name: FULL_NAME
            value: {{ template "vault.fullname" . }}
          - name: "VAULT_TLS_SERVER_NAME"
            value: "{{.Values.Vault.Tls.ServerName}}"
          - name: "VAULT_TLS_ALT_SERVER_NAMES"
            value: "{{.Values.Vault.Tls.AlternateServerNames}}"
          - name: ACME_ENVIRONMENT
            value: {{.Values.Vault.Tls.LetsEncrypt.Environment}}
          - name: ACME_ACCOUNT_KEY
            value: {{.Values.Vault.Tls.LetsEncrypt.AcmeAccountKey}}
        command:
        - "bash"
        - "-ec"
        - |
          chmod -R +x /pre-install
          /pre-install/generate-vault-cert.sh
          /pre-install/create-vault-secrets.sh
        volumeMounts:
        - name: pre-install
          mountPath: /pre-install
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: true
      volumes:
        - name: pre-install
          configMap:
            name: {{ template "vault.fullname" . }}-{{.Values.Vault.PreInstall.ComponentName}}
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
{{- end }}
