{{- if and .Values.Vault.Tls.CertString .Values.Vault.Tls.KeyString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.fullname" . }}.tls
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.Vault.Tls.CertString | b64enc }}
  tls.key: {{ .Values.Vault.Tls.KeyString | b64enc }}
{{- end }}
